---
version: '3.8'

services:
  api:
    image: morriz/doup:main
    ports:
      - 8888:8080
    restart: unless-stopped
    volumes:
      - ./bin:/app/bin
      - ./certs:/app/certs
      - ./data:/app/data
      - ./hostpipe:/hostpipe
      - ./hostpipe.txt:/app/hostpipe.txt
      - ./lib:/app/lib
      - ./proxy:/app/proxy
      - ./upstream:/app/upstream
    env_file:
      - .env
