openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /hook:
    post:
      summary: Webhook Handler
      operationId: webhook_handler_hook_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: string
                title: Response Webhook Handler Hook Post
  /update-upstream/{project}/{service}:
    get:
      summary: Get Hook Handler
      description: Handle requests to update the upstream
      operationId: get_hook_handler_update_upstream__project___service__get
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: path
        required: true
        schema:
          type: string
          title: Project
      - name: service
        in: path
        required: true
        schema:
          type: string
          title: Service
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /update-upstream/{project}:
    get:
      summary: Get Hook Handler
      description: Handle requests to update the upstream
      operationId: get_hook_handler_update_upstream__project__get
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: path
        required: true
        schema:
          type: string
          title: Project
      - name: service
        in: query
        required: false
        schema:
          type: string
          title: Service
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /projects/{project}:
    get:
      summary: Get Projects Handler
      description: Get the list of all or one project
      operationId: get_projects_handler_projects__project__get
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: path
        required: true
        schema:
          type: string
          title: Project
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project-Output'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /projects:
    get:
      summary: Get Projects Handler
      description: Get the list of all or one project
      operationId: get_projects_handler_projects_get
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: query
        required: false
        schema:
          type: string
          title: Project
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project-Output'
                title: Response Get Projects Handler Projects Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - Project
      summary: Upsert Project Handler
      description: Create or update a project
      operationId: upsert_project_handler_projects_put
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project-Input'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - Project
      summary: Upsert Project Handler
      description: Create or update a project
      operationId: upsert_project_handler_projects_post
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project-Input'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /projects/{project}/services/{service}:
    get:
      summary: Get Project Services Handler
      description: Get the list of a project's services, or a specific one
      operationId: get_project_services_handler_projects__project__services__service__get
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: path
        required: true
        schema:
          type: string
          title: Project
      - name: service
        in: path
        required: true
        schema:
          type: string
          title: Service
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /projects/{project}/services:
    get:
      summary: Get Project Services Handler
      description: Get the list of a project's services, or a specific one
      operationId: get_project_services_handler_projects__project__services_get
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: path
        required: true
        schema:
          type: string
          title: Project
      - name: service
        in: query
        required: false
        schema:
          type: string
          title: Service
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
                title: Response Get Project Services Handler Projects  Project  Services
                  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /projects/{project}/services/{service}/env:
    get:
      summary: Get Env Handler
      description: Get the list of a project's service' env vars
      operationId: get_env_handler_projects__project__services__service__env_get
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: path
        required: true
        schema:
          type: string
          title: Project
      - name: service
        in: path
        required: true
        schema:
          type: string
          title: Service
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Env'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    patch:
      tags:
      - Env
      summary: Patch Env Handler
      description: Update env for a project service
      operationId: patch_env_handler_projects__project__services__service__env_patch
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: path
        required: true
        schema:
          type: string
          title: Project
      - name: service
        in: path
        required: true
        schema:
          type: string
          title: Service
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Env'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /services:
    get:
      summary: Get Services Handler
      description: Get the list of all services
      operationId: get_services_handler_services_get
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
                title: Response Get Services Handler Services Get
    put:
      tags:
      - Service
      summary: Upsert Service Handler
      description: Create or update a service
      operationId: upsert_service_handler_services_put
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: query
        required: true
        schema:
          type: string
          title: Project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - Service
      summary: Upsert Service Handler
      description: Create or update a service
      operationId: upsert_service_handler_services_post
      security:
      - APIKeyQuery: []
      - APIKeyHeader: []
      - HTTPBearer: []
      parameters:
      - name: project
        in: query
        required: true
        schema:
          type: string
          title: Project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Env:
      properties: {}
      additionalProperties: true
      type: object
      title: Env
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Project-Input:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        domain:
          type: string
          title: Domain
        entrypoint:
          type: string
          title: Entrypoint
        services:
          items:
            $ref: '#/components/schemas/Service'
          type: array
          title: Services
          default: []
      type: object
      required:
      - name
      title: Project
      description: Project model
    Project-Output:
      properties:
        name:
          type: string
          title: Name
        description:
          type: string
          title: Description
        domain:
          type: string
          title: Domain
        entrypoint:
          type: string
          title: Entrypoint
        services:
          items:
            $ref: '#/components/schemas/Service'
          type: array
          title: Services
          default: []
      type: object
      required:
      - name
      title: Project
      description: Project model
    Service:
      properties:
        command:
          type: string
          title: Command
        env:
          allOf:
          - $ref: '#/components/schemas/Env'
        image:
          type: string
          title: Image
        labels:
          items:
            type: string
          type: array
          title: Labels
          default: []
        name:
          type: string
          title: Name
        passthrough:
          type: boolean
          title: Passthrough
          default: false
        path_prefix:
          type: string
          title: Path Prefix
        path_remove:
          type: boolean
          title: Path Remove
          default: false
        port:
          type: integer
          title: Port
          default: 8080
        proxyprotocol:
          type: boolean
          title: Proxyprotocol
          default: true
        volumes:
          items:
            type: string
          type: array
          title: Volumes
          default: []
      type: object
      required:
      - name
      title: Service
      description: Service model
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    APIKeyQuery:
      type: apiKey
      in: query
      name: apikey
    APIKeyHeader:
      type: apiKey
      in: header
      name: X-API-KEY
    HTTPBearer:
      type: http
      scheme: bearer
