---
version: '3.8'

networks:
  proxynet:
    name: proxynet
    driver: bridge
    driver_opts:
      encrypted: 'true'

services:
  proxy:
    image: nginxinc/nginx-unprivileged:stable
    networks:
      - default
    ports:
      - 8443:8443
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ../data:/data
      - ./nginx/map:/etc/nginx/map:ro
      - ./nginx/proxy.conf:/etc/nginx/nginx.conf:ro

  terminate:
    image: nginxinc/nginx-unprivileged:stable
    # user: 101:101
    depends_on:
      - proxy
    networks:
      - default
      - proxynet
    expose:
      - '8443'
    restart: unless-stopped
    volumes:
      - ../certs:/certs
      - ./nginx/map:/etc/nginx/map:ro
      - ./nginx/terminate.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
