name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  uptid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install and activate venv
        run: python -m venv .venv

      - name: Install dependencies
        run: bin/requirements-update.sh

      - name: Run checks
        run: |
          bin/format.sh
          bin/lint.sh
          bin/test.sh
